### ISSUE TITLE
HR Diagram Unit Test failing

### ISSUE THREAD

**Issue by mcoughlin** [ZwickyTransientFacility/scope#107]
/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pandas/core/arraylike.py:397: RuntimeWarning: invalid value encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)
/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pandas/core/arraylike.py:397: RuntimeWarning: invalid value encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)
Traceback (most recent call last):
[·] Generating HR diagrams for Golden sets
  File "/home/runner/work/scope/scope/./scope.py", line 755, in <module>
    fire.Fire(Scope)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/runner/work/scope/scope/./scope.py", line 424, in doc
    plot_gaia_hr(
  File "/home/runner/work/scope/scope/scope/utils.py", line 243, in plot_gaia_hr
    ax.errorbar(
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/matplotlib/__init__.py", line 1423, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line [35](https://github.com/ZwickyTransientFacility/scope/actions/runs/3070998186/jobs/4961288596#step:6:36)87, in errorbar
    raise ValueError(
ValueError: 'yerr' must not contain negative values
[✗] Generating HR diagrams for Golden sets

**Comment by bfhealy** [comment]
@mcoughlin it looks like there's a sign error in line 246 of utils.py:
`gaia_data["M"] - gaia_data["Ml"],`
should be flipped.

But I'm having trouble reproducing the error you posted above. I get several of
`RuntimeWarning: invalid value encountered in log10`
during the HR diagram generation while when running `./scope.py doc`, but no ValueError.

**Comment by mcoughlin** [comment]
@bfhealy Maybe a version thing with the requirements in the Github Actions?

**Comment by bfhealy** [comment]
@mcoughlin That's possible. I guess we could make the sign change and see what happens with the Action after that?

**Comment by mcoughlin** [comment]
@bfhealy yeah seems like a good idea.

**Comment by mcoughlin** [comment]
Seems like we fixed this.
