### ISSUE TITLE
Period-finding sometimes loops over incorrect number of sources

### ISSUE THREAD

**Issue by bfhealy** [ZwickyTransientFacility/scope#314]
In the examples below, the "Analyzing lightcurves" part of the code loops over fewer light curves than were requested to be downloaded in the "Getting lightcurves" part of the script. This may be due to some batch Kowalski queries (max 10,000 sources each) failing to return light curves:

```
Getting lightcurves...
56457 done
Analyzing lightcuves and computing basic features...
10000 done
20000 done
20000 done
Running period algorithms for 55432 sources in batches of 1000...
```

```
Getting lightcurves...
200000 done
362489 done
Analyzing lightcuves and computing basic features...
10000 done
20000 done
30000 done
40000 done
50000 done
60000 done
70000 done
80000 done
90000 done
100000 done
110000 done
120000 done
130000 done
140000 done
150000 done
160000 done
170000 done
180000 done
190000 done
200000 done
210000 done
220000 done
230000 done
240000 done
250000 done
252489 done
Running period algorithms for 275577 sources in batches of 1000...
Running ECE algorithm:
Iteration 1 of 276...
Period finding lightcurves...
Number of lightcurves: 1000
Max length of lightcurves: 427
...
Iteration 166 of 276...
Period finding lightcurves...
Number of lightcurves: 577
Max length of lightcurves: 423
Batch size: 1000
Number of frequency bins: 8183767
Number of phase bins: 20
Number of magnitude bins: 10
Iteration 167 of 276...
Period finding lightcurves...
Number of lightcurves: 0
```

The feature generation code currently defines the dictionary of source IDs to analyze assuming that the length of the light curve query results will be the same. This causes a point in the period-finding loop where no light curves are passed in. This raises the following error, which stops the script:

```
Traceback (most recent call last):
  File "/home/bhealy/scope/tools/generate_features.py", line 878, in <module>
    generate_features(
  File "/home/bhealy/scope/tools/generate_features.py", line 528, in generate_features
    periods, significances, pdots = periodsearch.find_periods(
  File "/home/bhealy/scope/tools/featureGeneration/periodsearch.py", line 328, in find_periods
    print("Max length of lightcurves: %d" % maxn)
OverflowError: cannot convert float infinity to integer
```

**Comment by bfhealy** [comment]
This turned out to be a Kowalski issue with batching, but stability improvements since then have effectively mitigated this issue.
